package com.openclassrooms.magicgithub.api;

import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

import com.openclassrooms.magicgithub.model.User;

import java.util.List;

/**
 * La classe FakeApiService implémente l'interface ApiService.
 * Un objet de type FakeApiService est donc également un objet de type ApiService
 */

public class FakeApiService implements ApiService {

    private final List<User> users = generateUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        // TODO: A modifier
        return users;
        //return null;

    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        this.getUsers().add(User.random());
        // TODO: A modifier
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: A modifier
         users.remove(user);
    }
}
